[env:feather_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit LSM6DS
    adafruit/Adafruit SGP41
    adafruit/Adafruit BME680 Library
    sensirion/Sensirion I2C SCD4x
    adafruit/Adafruit MAX1704X
