[env:feather_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
upload_speed = 921600
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DPAQETT_FIRMWARE_VERSION=\"1.0.0\"
    -DPAQETT_DEBUG=1
    -DPAQETT_MQTT_NO_TLS=1
    -DWIFI_SSID=\"BTHub5-JQX6\"
    -DWIFI_PASSWORD=\"9be2479be2\"
    -DAPI_URL=\"http://192.168.1.240:3000\"
    -DAPI_KEY=\"paq_key_d6b444c5388ab64c2546880beff14ea9d6810eeb30bdae35\"
lib_deps =
    adafruit/Adafruit LSM6DS
    adafruit/Adafruit SGP41
    adafruit/Adafruit BME680 Library
    sensirion/Sensirion I2C SCD4x
    adafruit/Adafruit MAX1704X
    adafruit/Adafruit NeoPixel
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    paqett-device-sdk=symlink:///Users/alessio/Documents/GitHub/paqett-device-sdk/device
